logging:
  level:
    com.syalar: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
    database: mysql
    show-sql: true